[package]
name = "rclient"
version = "0.1.0"
authors = ["Alexey Pashinov <pashinov93@gmail.com>"]
edition = "2018"

[dependencies]
zmq = "0.9.0"
protobuf = "2.5.0"
config = "0.9.3"
daemonize = "0.4.1"
signal-hook = "0.1.9"
log = "0.4.6"
log4rs = "0.8.3"
